import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "components/Navbar";
import Footer from "components/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hexagon Hustle House</title>
        <meta name="description" content="Generated by create next wagmi dapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
      <h1 className="text-center text-3xl font-bold underline">
        TailwindCSS Ready Template
      </h1>
      </div>
      <Footer />
    </div>
  );
};

export default Home;
