import { BasciConnect } from "components/ConnectWallet";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Hexagon Hustle House</title>
                <meta name="description" content="Generated by create next wagmi dapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex px-2 py-2 justify-end">
                <BasciConnect />
            </div>
                <h1 className="text-center text-3xl font-bold underline">
    TailwindCSS Ready Template
  </h1>
            
        </div>
    );
};

export default Home;
